# Generated by Django 6.0.3 on 2026-05-25 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedores', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fornecedor',
            old_name='cpnj',
            new_name='cnpj',
        ),
    ]
