# Generated by Django 6.0.3 on 2026-05-04 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0002_ordemserviços'),
        ('funcionarios', '0001_initial'),
        ('servicos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrdemServiços',
            new_name='OrdemServicos',
        ),
        migrations.AddField(
            model_name='agendamento',
            name='servicos',
            field=models.ManyToManyField(through='agendamentos.OrdemServicos', to='servicos.servico', verbose_name='Serviço'),
        ),
    ]
