# Generated by Django 6.0.3 on 2026-05-06 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_alter_produto_options'),
        ('servicos', '0002_alter_servico_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servico',
            name='produtos',
        ),
        migrations.AddField(
            model_name='servico',
            name='produto',
            field=models.ManyToManyField(null=True, related_name='servico_produtos', through='servicos.ProdutosServico', to='produtos.produto'),
        ),
        migrations.AddConstraint(
            model_name='produtosservico',
            constraint=models.UniqueConstraint(fields=('servico', 'produto'), name='constraint_produto_servico'),
        ),
    ]
