# Generated by Django 6.0.3 on 2026-05-06 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0003_remove_servico_produtos_servico_produto_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servico',
            old_name='produto',
            new_name='produtos',
        ),
    ]
